### ISSUE TITLE
A problem with initializing databases - code 255

### ISSUE THREAD

**Issue by blooria** [phac-nml/mob-suite#118] opened 2022-09-18 11:48 UTC
I am having problems running mob_suite
installed with:
% git clone https://github.com/phac-nml/mob-suite.git
% cd mob-suite
% python setup.py install

I get a error code 255 
Please help me fix this.
Thank you

**Comment by jrober84** [comment] 2022-09-20 13:31
Hello,

please try installing using conda as there are other external programs you will need to have installed as well.

% conda config --add channels defaults
% conda config --add channels conda-forge
% conda config --add channels bioconda
% conda install -c bioconda mob_suite

**Comment by kbessonov1984** [comment] 2022-09-20 15:38
Hello,

Code 255 usually means that remote server is down. Perhaps our database hosting zenodo.org was down at the time you tried to install the tool?

I was not able to reproduce your error in a Docker container by cloning the `master` branch source code and running  install on a fresh Ubuntu 20.04. In my case all dependencies and databases initialize with no errors. 

To help you with the install from the source code, the `Dockerfile` is available at [`mob_suite/docker/Dockerfile`](https://github.com/phac-nml/mob-suite/blob/01af70d0bd47c7cf061e3fb20e934527c3800b14/mob_suite/docker/Dockerfile). It allows to build a local image of a tool and has all step by step commands to install locally. Due to large `ete3` library taxonomy dependency, `mob_init` takes awhile to initialize. As an option you can save time and pull Docker and Singularity images with initialized database available from https://biocontainers.pro/tools/mob_suite and https://hub.docker.com/r/kbessonov/mob_suite

**Comment by jrober84** [comment] 2022-12-07 17:00
I am marking this as closed for now

**Closed by jrober84** 2022-12-07 17:00 UTC
